### ISSUE TITLE
Newbie needs help!

### ISSUE THREAD

**Issue by DiabolicAngeL** [naice/MedievalDynastyMap#2]
Hello, I followed the main (I think) but when I open in my browser the map the cities looks like this 
![image](https://user-images.githubusercontent.com/68332732/102717455-08f5b400-42eb-11eb-8a95-5f26a37cdd21.png)

Browser console
![image](https://user-images.githubusercontent.com/68332732/102719309-0b114000-42f6-11eb-9b35-41a38294984b.png)

Server console
![image](https://user-images.githubusercontent.com/68332732/102719329-1fedd380-42f6-11eb-9735-f4033973b65d.png)

and the editor doesn't work. Am I missing something?

Thanks a lot!

Edit:

The problem is here:
/src/app/city-jumper/city-jumper.component.html
``<span matLine>{{city.payload.name}}</span>``

When I remove `name` it works, but it doesn't display names on the city jumper. I have no idea what to do xD

**Comment by naice** [comment]
I have fixed it, just refresh the browser :)

**Comment by DiabolicAngeL** [comment]
Sorry I re-open it, Any plans to make it work on mobile? x))

**Comment by naice** [comment]
I wanted to, but there are no requests except yours and the participation is very low unfortunatly.

**Comment by DiabolicAngeL** [comment]
Oh, that's sad :(

Thank you very much anyway. I love it!
